###
### REPORTING / EQUITY-TEP1014
###
[kernel]
strict = false
audit = { mode = false, hash = "SHA-256" }
timestamp = { default-time = 00:00:00, timezone = { name = "UTC" } }

[kernel.input]
storage = "fs"

[kernel.input.fs]
dir = "txns"
suffix = "txn"

[transaction]
accounts    = { path = "ok-accounts.toml" }
commodities = { path = "ok-commodities.toml" }
tags        = { path = "none" }


[report]
report-timezone = "UTC"
scale = { min = 0, max = 28 }
accounts = [ "^a0(:.*)?" ]
targets = [ "balance" ]

balance       = { title = "BALANCE" }
balance-group = { title = "BALANCE GROUPS", group-by = "date" }
register      = { title = "REGISTER" }


[export]
targets = ["equity" ]
equity = { equity-account = "Eq:Acc" }
