### vim: tabstop=4 shiftwidth=4 softtabstop=4 smarttab expandtab autoindent
###
### PRICE / OK: COMMODITIES
###

permit-empty-commodity = true

commodities = [
    "$",
    "aaa",
    "bbb",
    "ccc",
    "TCKLR",
]
