###
### PARSER / ACC-NAMES
###
[kernel]
strict = true
audit = { mode = false, hash = "SHA-256" }
timestamp = { default-time = 00:00:00, timezone = { name = "UTC" } }

[kernel.input]
storage = "fs"

[kernel.input.fs]
dir = "txns"
suffix = "txn"

[transaction]
accounts    = { path = "acc-names-accounts.toml" }
commodities = { path = "acc-names-commodities.toml" }
tags        = { path = "none" }


[report]
report-timezone = "UTC"
scale = { min = 0, max = 7 }
accounts = [ ]
targets = [ ]

balance       = { title = "BALANCE (TEST)" }
balance-group = { title = "BALANCE GROUP (TEST)", group-by = "date" }
register      = { title = "REGISTER (TEST)" }


[export]
targets = [ "identity" ]
equity = { equity-account = "Equity:Balance" }
